### ISSUE TITLE
Webif is broken after compilation

### ISSUE THREAD

**Issue by dystopia2017** [GruberMarkus/Build-OSCamForWindows#3]
Webif after compilation gives error 403 forbidden. During installation webif get's patched according to the log

patching file webif/config/dvbapi.html
patching file globals.h

Is there someway to prevent this?

**Comment by GruberMarkus** [comment]
I just executed the script on Windows 11 (with all recent patches), using Windows PowerShell as well as PowerShell 7. A standard user without administrative permissions was used.

After the build, I executed .\oscam-exe\oscam.exe.

In both cases I could not reproduce the problem, as the web interface on localhost:8888 was accessible without a problem.


Can you reproduce the problem by starting .\oscam-exe\oscam.exe with the default configuration (without applying any existing configuration or changing the default configuration)?

**Comment by dystopia2017** [comment]
I believe the issue was my fault, I edited the script to add another patch. I added a line here so this

`patch -p0 < oscam-emu.patch`

became this

```
patch -p0 < oscam-emu.patch
patch -p0 < T:\\0001-Add-altcsa-extended-cw-mode.patch
```

The patch i was adding is here https://pastebin.com/raw/QbHD15kx
I am still unsure why webif is getting patched as it's not supposed to be getting touched but I guess the issue is my fault for adding a second patch.

**Comment by GruberMarkus** [comment]
I would try the following:
1. Do not apply the `oscam-emu.patch` path, but only the `0001-Add-altcsa-extended-cw-mode.patch` patch.
2. If (1) works, apply `0001-Add-altcsa-extended-cw-mode.patch` before `oscam-emu.patch`.
3. If (1) or (2) does not work, inform the creators of `0001-Add-altcsa-extended-cw-mode.patch`, as they will know best which side effects their code changes may bring and how to avoid them.


As the root cause is not within Build-OSCamForWindows: Is it ok for you if I close this issue?

**Comment by dystopia2017** [comment]
Yes and thank you for the advice.
